version: 2.1
jobs:
  build:
    docker:
      - image: gocv/opencv:4.5.0
    working_directory: /usr/local/go/src/github.com/hybridgroup/gocv
    environment:
        DISPLAY: 99.0
    steps:
      - checkout
      - run:
          name: Check Go version
          command: go version
      - run:
          name: Install xvfb
          command: |
            apt-get update -yqq && apt-get install xvfb -y
      - run:
          name: Run xvfb
          command: sh -e /etc/init.d/xvfb start
          background: true
      - run:
          name: Run tests
          command: make test
